[package]
name = "display-blocking"
version = "0.1.0"
edition = "2018"

[dependencies]
cortex-m = { version = "0.7.6", features = ["critical-section-single-core"]}
cortex-m-rt = "0.7.3"
panic-halt = "0.2.0"
defmt-rtt = "0.4.0"
defmt = "0.3.5"
microbit-v2 = "0.13.0"
